http://localhost:8080/coffee/resources/choix/

###
POST http://localhost:8080/coffee/resources/choix/
Content-Type: application/json

{
    "name": "Espresso",
    "price": 2.0
}

###
POST http://localhost:8080/coffee/resources/choix/
Content-Type: application/json

{
    "name": "Ristretto",
    "price": 1.5
}

###
POST http://localhost:8070/coffee/resources/choix/
Content-Type: application/json

{
    "name": "Lungo",
    "price": 3.0
}

###
DELETE http://localhost:8080/coffee/resources/choix/Espresso

###
GET http://localhost:8080/coffee/resources/choix/Ristretto

###
PUT http://localhost:8080/coffee/resources/choix/
Content-Type: application/json

{
  "name": "Ristretto",
  "price": 3.0
}
